spring:
  datasource:
    username: test
    password: 1234
    url: jdbc:mysql://localhost/bob
#spring:
#  datasource:
#    username: minsung
#    password: dhalstjd1
#    url: jdbc:mysql://localhost/minsung
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: always


jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK